version: 2
updates:
    - package-ecosystem: docker
      directory: /
      schedule:
        interval: daily
        time: "04:00"
      labels:
        - dependencies
        - docker
      reviewers:
        - Fank
      commit-message:
        prefix: chore
        include: scope
    - package-ecosystem: github-actions
      directory: /
      schedule:
        interval: daily
        time: "04:00"
      labels:
        - dependencies
        - github-actions
      reviewers:
        - Fank
      commit-message:
        prefix: chore
        include: scope
